[package]
name = "rust-option-result"
version = "0.1.0"
authors = ["Raphael Santo Domingo <raphael.santodomingo@target.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
